### PR TITLE
Further JSON salt improvements, and other fixes :)

### PR DESCRIPTION
**Pull request by novemberborn**
Documented JSON salts (see #3). Added type checks. And making sure we can test Node v6 in CI.

@jamestalmage perhaps you could take a look?

### CODE REVIEW

**Comment by jamestalmage** [comment]
I wouldn't allow Objects, and for Arrays, only allow Arrays of Strings (pass the array of strings straight to md5-hex - it will be more efficient than stringifying the array).

There are just too many.gotchas when stringifying an object for it to be reliable:

``` js
{a: 'a', b: 'b'}
// vs
{b: 'b', a: 'a'}
```

``` js
{a: 'a', b: undefined}
// vs
{a: 'a'}
```

**Comment by novemberborn** [comment]
@jamestalmage but then why suggest #3?

If efficiency is a concern then calling code should construct a buffer and not pass arrays / objects.

**Comment by jamestalmage** [comment]
Oh. Hehe. I disagree with myself on this one apparently.

I did mention the ambiguity at the top of #3. The point I make there is probably valid. (These ambiguities are only going to create false misses, so likely no big deal).

---

I should have said Array of Buffers or Strings, but if you're going to allow Objects then nevermind

**Comment by novemberborn** [comment]
> I did mention the ambiguity at the top of #3. The point I make there is probably valid. (These ambiguities are only going to create false misses, so likely no big deal).

Yea. As I said in #3:

> It's likely that without this calling code would stringify objects on their own, exposing themselves to the same ambiguity.

---

Any other feedback on these changes?

**Comment by jamestalmage** [comment]
🎉

**Pull request merged**
